### ISSUE TITLE
SyntaxError: Unexpected token m

### ISSUE THREAD

**Issue by rattrayalex** [filepicker/filepicker-js#22] opened 2016-02-02 02:46 UTC
Traceback provided by rollbar: 

```
SyntaxError: Unexpected token m
1
File "(native)" line (unknown) in Object.parse
2
File https://api.filepicker.io/v2/filepicker.js line 2 col 11437 in Object.decode
3
File https://api.filepicker.io/v2/filepicker.js line 1 col 215 in Object.function.r.isClass.n.(anonymous
4
File https://api.filepicker.io/v2/filepicker.js line 1 col 1090 in i
```

Primarily found in various versions of Chrome. 

Hope this is helpful! Thanks!

**Comment by krystiangw** [comment] 2016-02-05 11:50
@rattrayalex Any more details? How to reproduce an error? You can use [non-minified script version](https://api.filepicker.io/v2/filepicker-2.4.0.js) for debugging.

**Comment by rattrayalex** [comment] 2016-02-09 17:55
Hey @krystiangw, unfortunately, we're unable to reproduce or put unminified scripts into prod. Wish I could help more; I know it's frustrating to receive undetailed bug reports like these! You're welcome to close if you don't have any hunches about what this might be.

**Comment by krystiangw** [comment] 2016-02-10 11:08
@rattrayalex I'm closing it for now but reopen it if you find any further details.

**Closed by krystiangw** 2016-02-10 11:08 UTC

**Comment by 40thieves** [comment] 2016-10-17 14:38
We're also seeing this issue (although on v1), reported by Sentry:

```
SyntaxError: Unexpected token s in JSON at position 0
  at Object.f(/v1/filepicker.js:1:27460)
  at Object.d.(anonymous function) [as parse](/v1/filepicker.js:1:226)
  at e(/v1/filepicker.js:1:7342)
```

I'm afraid we can't offer much more detail either as I can't reproduce on development and can't use the unminified version in production. Sorry about that :(

According to our reporting it does seem that this issue has jumped up quite significantly since 2nd Oct and I can't see any deploys/changes that we made that might have affected it. Also it does appear to be affecting Chrome only.

I'm going to try upgrading to v2 now to see if that resolves the issue.

**Comment by IanVS** [comment] 2016-11-11 03:05
I have been seeing these errors periodically as well (v1).  In fact I just got 11,000 of them from a single user over the course of about two hours.  The stacktrace I get from TrackJS looks like:

```js
var f = function(b, c) {
    if (!b || a.util.typeOf(b) != 'string') return null;
    if (window.JSON && window.JSON.parse) return window.JSON.parse(b);
    else {
      if (c)
        if (!d(b)) throw new Error('JSON could not decode the input; security is enabled and the value is not secure.');
      return eval('(' + b + ')'
```

With the error occurring on the `window.JSON.parse(b)`. 

Two steps up the trace is 

```js
var e = function(b) {
  if (b.origin != a.urls.BASE && b.origin != a.urls.DIALOG_BASE) return;
  var c = a.json.parse(b.data);
  a.handlers.run(c);
};
```

And that is being called from inside a New Relic user timing wrapper that I can't find an unminified version of.

**Comment by IanVS** [comment] 2016-11-11 03:21
Ah, so I notice in the unminified script that @krystiangw posted:

```js
  var communicationsHandler = function(event) {
        if (event.origin !== fp.urls.BASE && event.origin !== fp.urls.DIALOG_BASE) {
            return;
        }
        var data = fp.json.parse(event.data);
        fp.handlers.run(data);
    };
```

According to [MDN postMessage docs](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage), chrome puts the origin into `event.originalEvent`.  So, it seems that we may have a postMessage coming from another origin and is sneaking through the check.

**Comment by 40thieves** [comment] 2016-11-11 09:41
Apologies - I meant to report back on v2 upgrade and totally forgot. We've not had any reoccurrences since upgrading, so that does seem to be a viable fix
